on:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set release notes
        run: |
          echo "${{ github.event.release.body }}" > RELEASE-NOTES.txt

      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main

      - name: Set VERSION variable from release tag
        run: |
          TAG="${{ github.event.release.tag_name }}"
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}

      - name: Test
        run: dotnet test --configuration Release /p:Version=${VERSION} --no-build

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .

      - name: Push
        run: dotnet nuget push kurnakovv.TestAnalyzer.${VERSION}.nupkg --source https://nuget.pkg.github.com/kurnakovv/index.json --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# on:
#   push:
#     tags:
#     - "v[0-9]+.[0-9]+.[0-9]+"

# permissions:
#   contents: read
#   packages: write

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     timeout-minutes: 30
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#     - name: Verify commit exists in origin/main
#       run: |
#         git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
#         git branch --remote --contains | grep origin/main
#     - name: Set VERSION variable from tag
#       run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
#     - name: Build
#       run: dotnet build --configuration Release /p:Version=${VERSION}
#     - name: Test
#       run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
#     - name: Pack
#       run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
#     - name: Push
#       run: dotnet nuget push kurnakovv.TestAnalyzer.${VERSION}.nupkg --source https://nuget.pkg.github.com/kurnakovv/index.json --api-key ${GITHUB_TOKEN}
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
